### ISSUE TITLE
Move to utf8 raw string protocol port

### ISSUE THREAD

**Issue by Brutus5000** [FAForever/client#1123]
For ages the lobby server used to listen on port 5000 for UTF16 encoded QDataStreams.

A while ago we added an additional connection to port 5001 which uses UTF8 with raw strings (messages are separated via linebreaks). This should be the "way to go" in order to remove Qt dependencies from the lobby server and simplify FAF a little bit.

[There are no plans immediate plans to close port 5000. Also this might be just an intermediate step to remove to a completely different connection style such as Websockets.]

**Comment by Gatsik** [comment]
I believe you are talking about ports 8001 (QDataStream) and 8002 (utf-8), because the only value, that contains 5000 in the whole codebase is replay server port (15000). If so, it is already the case since version 0.20.0 ([commit](https://github.com/FAForever/client/commit/646c9bf7ae6d8490ac2d1adb7a66608b0e36e250))
https://github.com/FAForever/client/blob/646c9bf7ae6d8490ac2d1adb7a66608b0e36e250/src/config/production.py#L35

**Comment by Brutus5000** [comment]
Nice, thanks :)
