### ISSUE TITLE
Unable to close chat tab when kicked from a channel

### ISSUE THREAD

**Issue by VoRGoR** [FAForever/client#162]
If you are kicked from a channel you are then unable to close the tab of the channel.
Very minor, but it's there.

**Comment by HardlySoftly** [comment]
The channel tab x button remains, but clicking it doesn't close the tab.

Clicking x causes a message to the Server channel:

    [notonchannel: faforever.com->Softles]<channel_name>
    You're not on that channel


A message from:

    https://github.com/FAForever/client/blob/develop/src/chat/irclib.py#L1518

The kicked user can still type into the channel, although their messages only appear on their screen and no other input from the channel is forwarded to the user.  This error message appears on entering text:

    [cannotsendtochan: faforever.com->Softles]<channel_name>
    No external channel messages (<channel_name>)




Not able to fix at the moment since chat in develop isn't working at all.

**Comment by HardlySoftly** [comment]
on_investgation it seems _chatwidget.py is missing an on_kick method to handle kicks
