### ISSUE TITLE
Green chat highlight not consistent

### ISSUE THREAD

**Issue by VoRGoR** [FAForever/client#291]
It says quit.
It gives you a ping like you got pm'd, but doesn't tell you where. If you have 20 tabs open like I do a lot, that's really annoying XD 
Also some interesting stuff with green:

![testalsogreen](https://cloud.githubusercontent.com/assets/8906373/12874736/a221169a-cdd1-11e5-9df3-f591df59a072.PNG)
![greentext](https://cloud.githubusercontent.com/assets/8906373/12874735/9c04ad80-cdd1-11e5-8a7f-0c9fc4fbf46a.png)
![testalsogree2](https://cloud.githubusercontent.com/assets/8906373/12874737/a3ec7b2c-cdd1-11e5-8580-52bce8cc7536.PNG)

**Comment by HardlySoftly** [comment]
Green is the intended behaviour for chatters in your clan

**Comment by HardlySoftly** [comment]
Its a bug with the player id being passed to the channel on startup, the event passed into https://github.com/FAForever/client/blob/develop/src/chat/_chatwidget.py#L404 contains player name but not id.

As a result it defaults to unknown id, aka irc user.

The colours on rejoining are probably because it gets handled differently at that point since channel is already open, so the id will be passed correctly on join.

**Comment by arkitect-dev** [comment]
so a change to pass in the player id will fix the green text for clan members, but is this of any value? highlighting in PM chat doesnt seem useful, aeolus doesn't highlight clan green and clan chat would all be green...

need to identify what the intended behaviour is for green highlight to move forward with this issue.

**Comment by Wesmania** [comment]
I believe this is no longer valid after chat refactors. Reopen if still an issue.
