### ISSUE TITLE
Client Error

### ISSUE THREAD

**Issue by ghost** [FAForever/client#424]
Every time I try to start a game, it simply gives me an error message saying that an error occurred. Which Logs do I give?

**Comment by Crotalus** [comment]
`C:\ProgramData\FAForever\logs\forever.log`
`C:\ProgramData\FAForever\logs\game.log`

If logging isn't enabled in client there won't be a game.log though

**Comment by ghost** [comment]
Client Log:
https://drive.google.com/file/d/0B-eJ9-g_JUSDeDV0cmtlT2lUVG8/view?usp=sharing

Game Log:
https://drive.google.com/file/d/0B-eJ9-g_JUSDVGVRc1pfVUY3OVk/view?usp=sharing

Thanks! I would copy it directly into here, but it exceeded the maximum characters allowed.

**Comment by Crotalus** [comment]
Permission denied when writing to
`'C:\ProgramData\FAForever\bin\init_nonxt.lua'`

This is probably due to FAF being started with admin rights earlier, therefore the file permissions get messed up. The easiest way to fix this is to uninstall FAF and completely delete `C:\ProgramData\FAForever` folder.

After that re-install FAF and remember not to run it as admin (next released version of the client won't run at all with admin rights).

**Comment by ghost** [comment]
It worked. Thanks!
