### ISSUE TITLE
Coop Maps don't expand

### ISSUE THREAD

**Issue by Aerospacespark** [FAForever/client#462]
I notice a lot of times when I'm in coop, the maps doesn't want to expand for some reason, the enemy's can still get through like the map did expand but it didn't so it just sits there and takes a big shit.  Its really killing me, 5th time happen today wondering if someone can look into it dankz.

**Comment by duk3luk3** [comment]
If I remember correctly, this is due to coop map scripts being very prone to breakage mainly because they were not originally made for FAF. A lot of work has gone into this already, I believe mainly by @speed2CZ on the coop map side ( https://github.com/FAForever/fa-coop, https://github.com/FAForever/faf-coop-maps ) and by @aeoncleanse on the fafmod side ( https://github.com/FAForever/fa ).

Please open an issue in the https://github.com/FAForever/fa-coop repository with detailed reports and if possible logs and replays so it can be triaged there.

**Comment by speed2CZ** [comment]
Broken missions report into https://github.com/FAForever/faf-coop-maps please
