### ISSUE TITLE
Problem by rating delayed until last player leaves game

### ISSUE THREAD

**Issue by GrotheFAF** [FAForever/client#469]
Example: in a ladder game #5392494 my oponent was afk and was still showing as ingame long after the game ended... so no counting, no points. I played a 2nd ladder after that (I lost) ... after that the first game was finally closed. The points of the 2nd lost game are overwritten by the late acounting of the first (613 -> 605 -> 624)  ... admitted a rather rare case.

Shouldn't games be counted and reported wenn fa anounced 'game over' ?  (and not when last one left fa)

**Comment by duk3luk3** [comment]
This issue should be in fa repo (due to tradition) - server has to wait for results from all clients and can only trust the results if all of the clients agree, otherwise it would be easy to cheat or impossible to determine which client is telling the truth.

We definitely can't do anything about this in the client so I'm closing this.
