### ISSUE TITLE
ICE test client - FAF cannot be run as administrator error on startup

### ISSUE THREAD

**Issue by Nojoke185** [FAForever/client#487]
downloaded the test ICE client build from:

https://ci.appveyor.com/api/buildjobs/gidr2y96896qj061/artifacts/dist%2FForged%20Alliance%20Forever-0.11.60-win32.msi

installed the MSI over top of production client (ie. accepted default install options)
OS is windows 7 pro

after install ran the FAF shortcut from desktop and got below error

![image](https://cloud.githubusercontent.com/assets/16309355/20273531/954b75f6-aa89-11e6-8e19-4655f19370c9.png)

when close is selected the error below displays:

![image](https://cloud.githubusercontent.com/assets/16309355/20273252/741a2ac2-aa88-11e6-9cf5-17161f983d72.png)

faf log:

[forever.zip](https://github.com/FAForever/client/files/589871/forever.zip)

tried to add full control to the user for the path : C:\ProgramData\FAForever but no change in behavior seen

**Comment by duk3luk3** [comment]
@Crotalus you laid that egg :)

Apparently the check always returns true if user is in administrator group even if FAF is not run elevated, UAC off or on doesn't matter.

See also [the documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/bb776463%28v=vs.85%29.aspx): "Returns TRUE if the user is a member of the Administrator's group; otherwise, FALSE."

I'd guess releasing this change would break faf for 70% of our userbase.

**Comment by Viba** [comment]
Had same issue, previously I've run FAF with as admin. Fixed by giving full control to "users" for programdata/faforever and running it as non-admin. UAC is off, Win 10 Enterprise.

And yes, this admin check and folder access thing needs to be addressed before pushing to production.

**Comment by muellni** [comment]
#485 proposes, that the installer sets the permissions for `C:\ProgramData\FAForever`
In #484 I try to get a script run during installation. This script could also set these permissions. Any help on that is welcome...

**Comment by duk3luk3** [comment]
Oh, is the problem that Windows automatically elevates FAF when FAF tries to access `C:\ProgramData\FAForever` and that's why the check fails?

**Comment by duk3luk3** [comment]
I don't know if this library is in any usable state, but it exists: [PyWin32](http://timgolden.me.uk/pywin32-docs/contents.html) / [CheckTokenMemberShip](http://timgolden.me.uk/pywin32-docs/win32security__CheckTokenMembership_meth.html)

CheckTokenMembership is the correct method to test this. For C# code that does this see here: http://stackoverflow.com/questions/1220213/detect-if-running-as-administrator-with-or-without-elevated-privileges

**Comment by duk3luk3** [comment]
I think we also need to add a manifest to FAForever.exe to make sure Windows never elevates it.

* http://superuser.com/a/103012
* https://msdn.microsoft.com/en-us/library/bb756929.aspx

**Comment by duk3luk3** [comment]
Also: http://forums.faforever.com/viewtopic.php?p=134509#p134509

**Comment by GrotheFAF** [comment]
if it is just about forever.log, there should be something like this in log-rotation after log-rotation and new forever.log creation:
if ctypes.windll.shell32.IsUserAnAdmin():
 . os.system("icacls %ProgramData%\FAForever\logs\forever.log /setowner %USERNAME%")
 . os.system("icacls %ProgramData%\FAForever\logs\forever.log /reset")
I tested this (with dosbox, not in client code) and it works.

**Comment by duk3luk3** [comment]
The icacl calls are a good idea. I think the way we should try to implement it is this way:

* Set a global flag in the `IsUserAnAdmin()` flag
* In all codepaths where the client will exit (like global exception hook), perform the icacl calls if the global flag is set
* Perform `/setowner` and `/reset /t` icacls on the `APPDATA` dir (`C:\ProgramData\FAForever`)

(Instead of global flag the `IsUserAnAdmin()` check could also be ran again; it should never change during the run of the client... theoretically... or at least elevated execution should never be rescinded during the run of the client, once it's elevated it stays elevated)

**Comment by GrotheFAF** [comment]
setting that Admin flag should include a test that user (%USERNAME%) is not Administrator.
to cover crash, bluescreens and alike:
candidates for icals-insertions:
fa_path.lua:  https://github.com/FAForever/client/blob/develop/src/fa/path.py#L19
temp.fafreplay:  https://github.com/FAForever/client/blob/develop/src/replays/_replayswidget.py#L98
temp.scfareplay: https://github.com/FAForever/client/blob/develop/src/fa/replay.py#L43
more?

**Comment by muellni** [comment]
I fixed the permission problem on my system with code like this:
```
def check_data_path_permissions():
    if sys.platform == 'win32':
        data_path = Settings.get('client/data_path')
        import win32api
        import win32con
        import win32security

        my_user = win32api.GetUserNameEx(win32con.NameSamCompatible)

        sd = win32security.GetFileSecurity(data_path, win32security.OWNER_SECURITY_INFORMATION)
        owner_sid = sd.GetSecurityDescriptorOwner()
        name, domain, type = win32security.LookupAccountSid(None, owner_sid)

        owner = "%s\\%s" % (domain, name)

        if (my_user != owner):
            from util import admin
            admin.runAsAdmin(["takeown", "/f", data_path, "/r"])
            admin.runAsAdmin(["icacls", data_path, "/reset", "/T"])
```
