### ISSUE TITLE
Store plaintext passwords instead of hashes in the ini files

### ISSUE THREAD

**Issue by Wesmania** [FAForever/client#659]
Right now we store hashes instead of plaintext passwords in the ini files. From the security perspective it makes exactly no difference, but it makes the code for the login wizard needlessly hacky.
Changing this involves pretty much forgetting any remembered passwords (which some people could've forgotten), so any fix to this should be very loudly announced.

**Comment by micheljung** [comment]
It absolutely makes a difference. If I, for whatever reason, see the contents of that file and you use the same password somewhere else (e.g. Facebook, Gmail, etc.) I may be able to log in there. If I see the hashed password, however, this is not possible because I'm usually not able to get the original password from it.

Long term solution is to not store the password at all, but a JWT token instead.

**Comment by Wesmania** [comment]
Point taken. I suppose the login wizard code can be untangled independently.

**Comment by micheljung** [comment]
I'll close this then :)
