### ISSUE TITLE
uniqueID fails to modify PATH with KeyError

### ISSUE THREAD

**Issue by Wesmania** [FAForever/client#736]
AIx_Putin reported an issue with login on the forum after he moved to Windows 10. It boils down to PATH not being exported in os.environ, which causes uniqueID to throw a KeyError. It appears to be an issue with the os module - best way to fix it would be not to meddle with PATH at all, and instead find the full path to faf-uid.exe.

**Comment by duk3luk3** [comment]
We already have a bunch of people on Windows 10, why is this cropping up now?

**Comment by Wesmania** [comment]
It could be an unusual PATH setup, or maybe cyryllic characters in PATH - maybe Win10 localizes some directory name that Win7 didn't use to, or adds some localized directory to PATH.

**Comment by duk3luk3** [comment]
Well, the error is that the PATH variable is missing - it shouldn't be missing just because of non-ascii characters, unless we actually have a bug in the os library of the python version we use. I made a debug client that dumps the whole environment for this - https://ci.appveyor.com/api/buildjobs/8w7khxh674fq9arm/artifacts/dist%2FForged%20Alliance%20Forever-0.12.4-win32.msi - we need to diagnose that first. Maybe we also need to find a way to dump the "raw" environment, going around python os (maybe win32 library has something for that?) to rule out bug in python.

**Comment by Wesmania** [comment]
I think fixing the code to just not use PATH is both correct and less effort. It's a bug anyway to add things to PATH each time we call a function.

**Comment by duk3luk3** [comment]
Yes - good spot. I still think we should try to get to the bottom of this bug if possible.
