### ISSUE TITLE
Incompatibility of 0.16.0 with WinXP 32 bit 

### ISSUE THREAD

**Issue by ludewich** [FAForever/client#864]
Hi Experts,

I have a second computer and we use it to play locally. Our favourite game is Forged Alliance - so thanks for your maintenance and keeping this excellent game alive!

Yesterday, we downloaded the latest update (Client 0.16.0), installed it successfully -- and the second computer fails to start it because "FAForever.exe is no valid Win32 application". Restoring the previous client 0.14.0+2276 works fine. The issue is a windows popup; I believe it did not even start a log file.

I would appreciate it if you could restore compatibility with the old Windows XP 32 Bit system (Service Pack 3). I am happy to provide debug output as needed (including offending exe dependencies if this should be useful). But perhaps it is easy to identify the change in behavior as it is probably some new compiler option (64 bit ? Windows version requirement?).

In the hope of being able to continue using FAF in our setup,

Christian

PS
Please do not post answers of sorts "Install a decent Windows". I am fully aware that Windows XP is ancient, unsafe, is no longer maintained and is strongly discouraged. I decided to install it for the sake of playing FAF. That is all this computer will ever do; everything else will be done on some Linux on that machine.

**Comment by Wesmania** [comment]
We know about this issue. Unfortunately we just can't move to newer Python / Qt frameworks and support Windows XP at the same time - the problem lies with PyQt5 not supporting Windows XP and there's nothing we can do about it. We knew that a small percentage of people play on XP, but benefits of moving to python 3 and Qt 5 outweighted abandoning XP support, sorry. You can probably keep running client 0.14 if you want, it will be a while before we'll introduce backwards-incompatible changes.

Since you're using Linux, you can try running the client natively and Supcom via wine. I'm using the setup myself and it works very well. We have client packages for [arch](http://wiki.faforever.com/index.php?title=Setting_Up_FAF_Linux#Arch_Linux) and [gentoo](http://wiki.faforever.com/index.php?title=Setting_Up_FAF_Linux#Gentoo), and we had people pretty easily run the client from source on [Ubuntu 17.04](http://forums.faforever.com/viewtopic.php?f=2&t=4507&start=350).

**Comment by ludewich** [comment]
That is a pity for me and my partner, indeed. Thanks for the very fast response, though.

Some time ago (when I have set up that computer), I managed to run FAF under wine -- with limited success: it worked, but hover animations were gone and, I believe, some other shortcomings were present as well.  WinXP was the clear winner here.

I appreciate all your efforts in this software, so thanks. Thanks for the plan to keep compatibility for a while! May I ask you to consider 0.14 to be some kind of "probably long living revision" and think twice before breaking compatibility in the future? The small percentage of XP users will be grateful.

I'll experiment with wine eventually and will stick with 0.14 until I find a suitable replacement.

**Comment by Wesmania** [comment]
We don't really plan to officially support 0.14, it will eventually start breaking without warning. I don't know when it will happen - we would really like to finally roll out the ICE adapter for better connectivity, but I don't know how long it will take us.

As I mentioned, client 0.16.0 runs natively on Linux and uses wine to launch the game, you can give it a try.
