### ISSUE TITLE
Ladder map stats tab is non-functional

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/client#967]
The ladder map stats tab in the leaderboards tab is broken. All these broken tabs(tournaments, divisions etc.) make the client look really bad. Maybe add some "underconstruction" thing to them so it doesn't look as terrible to new players. Or just remove them.

**Comment by GrotheFAF** [comment]
These are all things we "lost in the fire" of Feb 2016.

**Comment by Wesmania** [comment]
That's what you get when the server relies on a bunch of loose php scripts tucked away in all sorts of places. That it didn't break before that is a miracle.

**Comment by GrotheFAF** [comment]
Not quite, these things were all (more or less) working before Feb 2016. The server update simply didn't support those features anymore.

**Comment by JaggedAppliance** [comment]
Yes it's true these things broke with the new Feb 2016 server, it doesn't explain why there's still all this broken stuff left in the client. It looks really bad, especially new players will think FAF is in a really bad state as a project.

**Comment by GrotheFAF** [comment]
Me, Me.. I know that history:
It was decided to let the python client rott and die, until a Don Quichote (me) came along to save it.
Sadly he was confronted with maintainers who care more about shiny code than shiny function... 
We don't know how it ends, but usually the windmills win.

**Comment by Wesmania** [comment]
You keep implying other client contributors are malicious and you're the only one doing useful work, and it's becoming overall more harmful than beneficial to the project. We have consistent issues with your code that would make the client less stable and harder to maintain, but you address them with hostility rather than with improvement.

Being able to work with people and not getting offended, hostile or outright paranoid over criticism or advice is part of being a good programmer. If you keep doing that I'll start refusing to merge your code - there's a point at which such behaviour detracts others from making contributions more than your own code is worth.

**Consider this a warning.**

**Comment by GrotheFAF** [comment]
you kinda made my point, if I don't agree with you I'm hostile, yes yes indeed ;-)
And what you think that I'm "implying" is just in your head.
(while you are the one with the name calling and the threats (see above), I don't do that)

**Comment by JaggedAppliance** [comment]
This is not the place for a discussion like this.

**Comment by Wesmania** [comment]
Agreed.

**Comment by Gatsik** [comment]
Ladder map stats tab is removed
